// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnO3GbAjMhbdvo-p_rd9H5l9XLp-VzJjo',
    appId: '1:180698664386:web:79806d61b8c77eaf889a5b',
    messagingSenderId: '180698664386',
    projectId: 'tdk-food-app',
    authDomain: 'tdk-food-app.firebaseapp.com',
    storageBucket: 'tdk-food-app.firebasestorage.app',
    measurementId: 'G-HV0E02G388',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtyirVDMGPjBjraEBd017vaUT-cxVRbak',
    appId: '1:180698664386:android:1ba65d59cd345aed889a5b',
    messagingSenderId: '180698664386',
    projectId: 'tdk-food-app',
    storageBucket: 'tdk-food-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGyQu3qlgdlqX288a_qLDzYZ46nLgfBQM',
    appId: '1:180698664386:ios:b3a885048267050b889a5b',
    messagingSenderId: '180698664386',
    projectId: 'tdk-food-app',
    storageBucket: 'tdk-food-app.firebasestorage.app',
    iosClientId:
        '180698664386-gcr7tls3gmq9japga95e6vqe15v9h6hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodMenu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGyQu3qlgdlqX288a_qLDzYZ46nLgfBQM',
    appId: '1:180698664386:ios:b3a885048267050b889a5b',
    messagingSenderId: '180698664386',
    projectId: 'tdk-food-app',
    storageBucket: 'tdk-food-app.firebasestorage.app',
    iosClientId:
        '180698664386-gcr7tls3gmq9japga95e6vqe15v9h6hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodMenu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnO3GbAjMhbdvo-p_rd9H5l9XLp-VzJjo',
    appId: '1:180698664386:web:9bef5b087451b2d5889a5b',
    messagingSenderId: '180698664386',
    projectId: 'tdk-food-app',
    authDomain: 'tdk-food-app.firebaseapp.com',
    storageBucket: 'tdk-food-app.firebasestorage.app',
    measurementId: 'G-DS200Q6179',
  );
}
